# Generated by Django 4.1.1 on 2022-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('auhor', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('isbn', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('pubished', models.CharField(default='', max_length=100)),
                ('pubisher', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
