# Generated by Django 4.1.1 on 2022-09-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_rename_pubished_books_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='auhor',
            new_name='author',
        ),
    ]
